---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployer-backend
  namespace: deployer

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployer-backend-role
  namespace: deployer
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "delete", "get", "list", "patch", "update"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["create", "delete", "get", "list", "patch", "update"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployer-backend-binding
  namespace: deployer
subjects:
  - kind: ServiceAccount
    name: deployer-backend
    namespace: deployer
roleRef:
  kind: Role
  name: deployer-backend-role
  apiGroup: rbac.authorization.k8s.io
